//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Department is required")]
        public Nullable<int> DepartmentId { get; set; }

        [Required(ErrorMessage ="First name is required")]
        [MaxLength(20,ErrorMessage ="Max lenght is 20 characters")]
        public string FirstName { get; set; }

        [Required(ErrorMessage ="Last name is required")]
        public string LastName { get; set; }

        [Required(ErrorMessage ="Email is required")]
        [EmailAddress(ErrorMessage ="Invalid email")]
        public string Email { get; set; }

        [Required(ErrorMessage ="Phone is required")]
        public string Phone { get; set; }

        [Required(ErrorMessage ="Birth date is required")]
        public Nullable<System.DateTime> BirthDate { get; set; }

        [Required(ErrorMessage ="Gender is required")]
        public Nullable<byte> Gender { get; set; }

        [Required(ErrorMessage ="Adress is required")]
        [MaxLength(50,ErrorMessage = "Max lenght is 20 characters")]
        public string Address { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
